Modifying error message for unsupported grant type
personium/personium-core pull request #595
Opened 2021-03-23 08:53 UTC by yoh1496

error message for unsupported grant type is defined as below

```
io.personium.core.msg.PR400-AN-0001=Unsupported grant type.{0}
```

But there is not code specifying the peram `{0}`.
I modified that

2021-03-24 03:30 UTC, tochi-y requested changes

2021-03-24 03:30 UTC, tochi-y commented on src/test/java/io/personium/test/jersey/cell/auth/AuthErrorTest.java
> +        String code = PersoniumCoreAuthnException.CLIENT_ASSERTION_PARSE_ERROR.getCode();
```suggestion
        String code = PersoniumCoreAuthnException.UNSUPPORTED_GRANT_TYPE.getCode();
```

2021-03-24 03:30 UTC, tochi-y commented on src/test/java/io/personium/test/jersey/cell/auth/AuthErrorTest.java
> +        String message = PersoniumCoreAuthnException.CLIENT_ASSERTION_PARSE_ERROR.getMessage();
```suggestion
        String message = PersoniumCoreAuthnException.UNSUPPORTED_GRANT_TYPE.getMessage();
```

2021-03-24 03:30 UTC, tochi-y commented on src/test/java/io/personium/test/jersey/cell/auth/AuthErrorTest.java
> +        checkErrorResponseBody(passRes, String.format(Error.UNSUPPORTED_GRANT_TYPE, unsupported_grant_type), errDesc);
Where does it check the message `Unsupported grant type. [unsupported_grant_type]`?

2021-04-01 01:06 UTC, yoh1496 commented
I modified codes. Could you review this again? @tochi-y

2021-04-05 01:09 UTC, tochi-y approved these changes

2021-04-05 01:09 UTC, merged